export const MASTER_DATA_CONFIG = [
  { key: "user", label: "Người sử dung" },
  { key: "permission", label: "Phân quyền" },
  { key: "tenor", label: "Kỳ hạn" },
  { key: "currency", label: "Tiền tệ" },
  { key: "denomination", label: "Mệnh giá" },
  { key: "allocation", label: "Dự chi/Phân bổ" },
  { key: "unit", label: "Đơn vị" },
  { key: "holiday", label: "Ngày nghỉ" },
  { key: "customer", label: "Khách hàng" },
  { key: "interest-type", label: "Loại  lãi suất" },
  { key: "partner", label: "Kênh đối tác" },
  { key: "secondary-intermediary", label: "Trung gian thứ cấp" },
  { key: "pricing-method", label: "Phương thức tính giá" },
  { key: "matching-method", label: "Phương pháp khớp lệnh" },
  { key: "product-configuration", label: "Cấu hình sản phẩm" },
  { key: "transaction-limit", label: "Hạn mức giao dịch" },
  { key: "product-room", label: "Room hàng" },
  { key: "other", label: "Danh mục khác" },
];
